apiVersion: v1
kind: Service
metadata:
  name: alpine-tor-service
  labels:
    deploy: alpine-tor
spec:
  type: NodePort 
  ports:
  - port: 9050
    targetPort: 9050
    protocol: TCP
    name: socks5
  selector:
    deploy: alpine-tor
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: alpine-tor
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: alpine-tor
  template:
    metadata:
      labels:
        deploy: alpine-tor
    spec:
      containers:
        - name: alpine-tor-proxy
          image: jfwenisch/alpine-tor
          env:
            name:mode
            value:"proxy"