FROM golang:alpine@sha256:68932fa6d4d4059845c8f40ad7e654e626f3ebd3706eef7846f319293ab5cb7a AS go-build

# Build /go/bin/obfs4proxy
RUN apk --no-cache add --update git \
 && git clone https://gitlab.com/yawning/obfs4.git \
 && cd obfs4 \
 && go build -o /usr/bin/obfs4proxy ./obfs4proxy

FROM python:alpine@sha256:b4d299311845147e7e47c970566906caf8378a1f04e5d3de65b5f2e834f8e3bf 
ENV EXPORTER_VERSION v0.3.3

RUN apk add tor --update-cache --repository http://dl-4.alpinelinux.org/alpine/edge/community
RUN wget https://raw.githubusercontent.com/H3rmt/tor-exporter/$EXPORTER_VERSION/prometheus-tor-exporter.py -O /prometheus-tor-exporter.py
RUN pip install stem prometheus_client retrying

COPY --from=go-build /usr/bin/obfs4proxy /usr/local/bin/obfs4proxy

COPY entrypoint.sh /entrypoint.sh
COPY start-exporter.sh /start.sh
RUN chmod +x /entrypoint.sh /start.sh

ENTRYPOINT [ "/bin/sh" , "entrypoint.sh" ]
